#!/bin/bash

ls /home/stanzu10/Dev/git
read -p "Which git directory: " FOLDER
cd /home/stanzu10/Dev/git/$FOLDER
git branch
cd /home/stanzu10/Dev/git/$FOLDER
git add .
git status
read -p "Enter commit name: " COMMIT
read -p "Description? (press enter or add description): " DESCRIPTION

git commit -m "commit $COMMIT" -m "$DESCRIPTION"  
git push 
git status

exit
