#!/bin/sh

ls /home/stanzu10/dev/git
read -p "Which git directory: " FOLDER
cd /home/stanzu10/dev/git/$FOLDER
git branch | bat 
cd /home/stanzu10/dev/git/$FOLDER
git add .
git status 
read -p "Enter commit name: " COMMIT
read -p "Description? (press enter or add description): " DESCRIPTION

git commit -m "$COMMIT" -m "$DESCRIPTION"  
git push 
git status 

exit
